contact_links:
    - name: â“ Questions and Help ğŸ¤”
      url: https://discord.gg/block-opensource (/add your discord channel if applicable)
      about: This issue tracker is not for support questions. Please refer to the community for more help. 
